#! /bin/sh
wmname LG3D &
pgrep -x sxhkd > /dev/null || sxhkd &
killall -9 sxhkd ksuperkey
killall -q picom
killall -9 dunst
killall -9 bspborder
killall polybar
killall bspborder

picom &
sxhkd &
/usr/bin/dunst &
xrandr --output DP-2 --primary
xrandr --output HDMI-0 --left-of DP-2 --mode 1920x1080
xrandr --output DP-2 --mode 1920x1080 -r 260


bspc monitor DP-2 -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         2
bspc config window_gap          10
bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      true
bspc config pointer_follows_focus false
bspc config focus_follows_pointer true
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Thunar state=tiled
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true

bspc config focused_border_color        "#252525"
bspc config normal_border_color         "#252525"
bspc config active_border_color         "#252525"
ksuperkey -e 'Super_L=Alt_L|F1' &

# xrandr --output `xrandcr | grep " connected"|cut -f1 -d" "`  --mode 1920x1080
xsetroot -cursor_name left_ptr &
feh --bg-fill --zoom centered ~/.config/bspwm/wall.png
polybar -c ~/.config/polybar/config.ini main
sleep 3s
xdo lower -N "Polybar"
xdo above -N "Polybar" -t $(xdo id -N Bspwm -n root)

